### ISSUE TITLE
Ingredients API routes returns duplicates

### ISSUE THREAD

**Issue by dukio** [Wynncraft/WynncraftAPI#12]
https://api.wynncraft.com/v2/ingredient/list
https://api.wynncraft.com/v2/ingredient/search/tier/0

This list returns each name two times, can easily be checked sorting the list or removing duplicates. There are 508 ingredients, 1016 on the returned json.

---
Edit: at first I thought it was only the list route, found out search/tier has the same issue... other routes might have it too

**Comment by dukio** [comment]
Updated, found another route with the same issue

**Comment by ColinRioux** [comment]
Patched in 2.0.1
