### ISSUE TITLE
Ingredients API missing skin, dropsFromLootChest

### ISSUE THREAD

**Issue by dukio** [Wynncraft/WynncraftAPI#13]
**About skin:**
Current ingredient API for Borange fluff (example, but all ingredients with a head sprite have this issue):
![image](https://user-images.githubusercontent.com/2744227/58134803-33bbea00-7c28-11e9-858d-6e7e490ee067.png)

Missing skin key (used in the items api as well as the [ingredients api substitute](https://pastebin.com/raw/P45Hb2Kv)):
`"skin": "eyJ0aW1lc3RhbXAiOjE0Mzc2OTU2MTU4NTMsInByb2ZpbGVJZCI6IjUwNzk4YjJhN2QxYjQxYTRiNmFlYzRiNWUwOWJjMTcxIiwicHJvZmlsZU5hbWUiOiJFbHN3ZXlyIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EwZmI0ZTZhNjEzMjJhNDE4NWU3YjQxYTY0M2Y2YTRjYjY5YTMxN2ViZTM5Mzk2ZmIyNzYyN2UzNjE0YzY5In19fQ==",`

----
**About dropsFromLootChest:**
[Ingredients API substitute](https://pastebin.com/raw/P45Hb2Kv) has `dropsFromLootChest: false` for ingredients that can not drop from lootchest. Something similar to this would be nice on the official API.
It could be the classic `dropType` field we are used to of the items API.

**Comment by ColinRioux** [comment]
I discussed this with Salted before the API went live and we decided to not expose this information any further. For dropsFromLootChest this is a firm no. I will discuss with Salted regarding the skin property.
