### ISSUE TITLE
Players API to include challenges for classes

### ISSUE THREAD

**Issue by dukio** [Wynncraft/WynncraftAPI#17]
So [challenges are being added to classes](https://forums.wynncraft.com/threads/who-here-is-the-most-hardcore-gamer.250389/) and it would be really cool if the Player API would return those information too for each player class.

Example:
```json
{
  "classes": [
    {
      "name": "archer",
      "challenges": {
        "hardcore": {
          "status": "alive"
        },
        "ironman": true,
        "craftsman": false
      }
    }
  ]
}
```

So `challenges` object contains a list of all the challenges with `true` if it's active or `false` if it's not. `Hardcore` is a special case since the player might have that challenge enabled but he failed it by dying.
Just wanted to give an example of how it could be implement, there are other ways of doing this and this might (probably is) not the best :stuck_out_tongue:

**Comment by ColinRioux** [comment]
Similar field added in patch 2.0.4
