### ISSUE TITLE
Player Stats: Guild information missing when requesting by UUID

### ISSUE THREAD

**Issue by Bedo9041** [Wynncraft/WynncraftAPI#18]
Example: https://api.wynncraft.com/v2/player/_Bedo_/stats has:
```js
guild: {
    name: "Darkguard",
    rank: "OWNER"
},
```
But https://api.wynncraft.com/v2/player/5aa0ae01-8c1b-4e0a-b31b-825389a7cb7b/stats has:
```js
guild: {
    name: null,
    rank: null
},
```

**Comment by ColinRioux** [comment]
Patched in v2.0.6
