### ISSUE TITLE
Leaderboard combat solo doesn't count xp after 104

### ISSUE THREAD

**Issue by dukio** [Wynncraft/WynncraftAPI#23]
I'll try to explain better:

https://www.wynndata.tk/stats/player/Glenncrafter

Glenncrafter top solo combat class in leaderboard is Mage (combat 104 8.7%, total level 1359) but his real top combat class is Hunter (combat 104 11.8%, total level 104).

I think this is due to leaderboard ordering classes by their combat level first, total level second instead of combat level first, combat xp second, total level third.

**Comment by ColinRioux** [comment]
I believe this is fixed. Reopen or comment if not.
