### ISSUE TITLE
API not updating usernames after name changes

### ISSUE THREAD

**Issue by Nitrogen2Oxygen** [Wynncraft/WynncraftAPI#29]
Recently, I've notice that the player API seems to not want to work with 2 players, `Lego_DW` and `Godenn`. Both of them recently changed their names from `TonTheTiger_` and `_regiTehTnoT` respectively. I've currently discovered that on the API, looking for the player stats of their new names will throw an error 400, whereas if you use their old names, it will give their normal stats, however, the guild field will always be null. When trying to use their uuids, the same will occur, with their stats popping up but their guild being null. Both users are in Kingdom Foxes at the moment, so their guilds should not be null. If any further investigation on this error is conducted, I'll be sure to post it here. 
Ty, Nitro

**Comment by Nitrogen2Oxygen** [comment]
Update: The player `zy5476` is having the same problem listed above, though he changed his name from `789poiu3` on 7/3/2019 (M/D/Y) which was over a month ago. Again, the stats for his current name don't show, but using his old name or his uuid work except the guild is null.

**Comment by Nitrogen2Oxygen** [comment]
Update 2: The player UUID endpoint only returns the correct UUID with the old username, implying that the name stored is in fact the old name. #9 actually might be linked to this issue as well, however, with my knowledge this is only a theory. Also, the player stored in the guild is in fact the new name, as seen from the legacy guild endpoint, implying that the name in the guild and the name stored with the stats are completely separate from each other. Finally, the other things on the player api that are wrong are as follows:
 - Player's current server cannot be found, but last join is mostly accurate
 - Player's leaderboard rankings seem to all return as `null`
Hope whatever is going on with you gets settled, and this hopefully get fixed in the near future

P.S. I'm REALLY bored, don't judge me for over-achieving on this report

**Comment by ColinRioux** [comment]
Hello!

You have done quite the research! This is less so an issue with the Wynncraft API and more so an issue with our name updater given the context. 

I want to make it clear now that the backend for the Wynncraft API will never request the Mojang API as we will get temporarily blacklisted in a matter of hours, and perhaps permanently blacklisted given the amount of requests made to the API on a given day. 

I have sent the report to our game dev and we will hopefully get this resolved. 

Thanks for reporting!

**Comment by Nitrogen2Oxygen** [comment]
Glad to see the issue finally being addressed. I know a good amount of people who will be happy for this fix.
