### ISSUE TITLE
404s actually have status code 200

### ISSUE THREAD

**Issue by Bedo9041** [Wynncraft/WynncraftAPI#54]
When making a request via an invalid route, the actual status code returned by the API is 200
Image:
![image](https://user-images.githubusercontent.com/7407004/96326839-2167fa80-102c-11eb-9c17-ce322e0e6ee6.png)
Example URL where the issue occurs: https://api.wynncraft.com/test

**Comment by colinrioux** [comment]
Will be fixed in a later version
